try a different compile script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -8,6 +8,9 @@ indent() {
 
 echo "-----> Install bws"
 BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
 VENDOR_DIR="vendor"
 DOWNLOAD_URL="https://github.com/bitwarden/sdk/releases/download/bws-v1.0.0/bws-x86_64-unknown-linux-gnu-1.0.0.zip"
 
@@ -18,7 +21,7 @@ mkdir -p $VENDOR_DIR
 cd $VENDOR_DIR
 
 # Download and unzip the file, with error handling
-if ! curl -L --fail --silent $DOWNLOAD_URL -o bws.zip; then
+if ! curl -L --fail $DOWNLOAD_URL -o bws.zip; then
   echo "Failed to download bws" | indent
   exit 1
 fi
@@ -35,3 +38,31 @@ echo 'export PATH="$PATH:$HOME/vendor/bws/bin"' >> $PROFILE_PATH
 echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/bws/lib"' >> $PROFILE_PATH
 
 echo "bws installation completed successfully" | indent
+
+# use bws to load the secrets
+
+if ! bws --version; then
+  echo "Failed to run bws" | indent
+  exit 1
+fi
+
+if [ ! -f "${ENV_DIR}/BW_ACCESS_TOKEN" ]; then
+    echo "BW_ACCESS_TOKEN was not set. Aborting" | indent
+    exit 1
+fi
+BW_ACCESS_TOKEN="$(cat "${ENV_DIR}/BW_ACCESS_TOKEN")"
+
+# Load secrets and export as environment variables
+bws secret list --access-token ${BW_ACCESS_TOKEN} | while read -r line; do
+  key=$(echo $line | cut -d' ' -f1)
+  value=$(echo $line | cut -d' ' -f2-)
+  echo "export $key=\"$value\""
+done > $BP_DIR/bws_secrets
+
+# Source the generated script to export the variables
+source $BP_DIR/bws_secrets
+
+# Delete the secrets file for security
+rm -f $BP_DIR/bws_secrets
+
+echo "bws secrets loaded successfully" | indent
